name: tests 
  
on: [push]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest  
    strategy:  
      matrix:  
        python-version: ["3.8", "3.9", "3.10"]  
  
    steps:  
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ matrix.python-version }}  
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ matrix.python-version }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          pip install .
      - name: Lint with Black  
        run: |  
          pip install black[jupyter] pytest pytest-cov
          black ./*
        continue-on-error: true  
      - name: Run and write pytest  
        run: |  
          cd tests
          set -o pipefail
          pytest --cov=simcat --cov-report term-missing -W ignore::UserWarning | tee pytest-coverage.txt
  
